package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
	"github.com/riyadennis/embedserver/graph/model"
	"github.com/riyadennis/embedserver/internal/chunker"
	"github.com/riyadennis/embedserver/internal/extractor"
	"github.com/riyadennis/embedserver/internal/store"
)

// Upload is the resolver for the upload field.
func (r *mutationResolver) Upload(ctx context.Context, file graphql.Upload) (*model.UploadResult, error) {
	// Persist to a temp file so the extractor can read it.
	tmp, err := os.CreateTemp("", "upload-*"+filepath.Ext(file.Filename))
	if err != nil {
		return nil, fmt.Errorf("create temp file: %w", err)
	}
	defer os.Remove(tmp.Name())
	defer tmp.Close()

	if _, err := io.Copy(tmp, file.File); err != nil {
		return nil, fmt.Errorf("save upload: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return nil, fmt.Errorf("close temp file: %w", err)
	}

	text, err := extractor.Extract(tmp.Name())
	if err != nil {
		return nil, fmt.Errorf("extract: %w", err)
	}
	if text == "" {
		return nil, fmt.Errorf("no text extracted from file")
	}

	chunks := chunker.Chunk(text, r.ChunkConf)
	if len(chunks) == 0 {
		return nil, fmt.Errorf("file produced no chunks")
	}

	vectors, err := r.Embedder.EmbedBatch(ctx, chunks)
	if err != nil {
		return nil, fmt.Errorf("embed: %w", err)
	}

	fileID := uuid.NewString()
	records := make([]store.Chunk, len(chunks))
	for i, c := range chunks {
		records[i] = store.Chunk{
			FileID:     fileID,
			Filename:   file.Filename,
			ChunkIndex: i,
			Text:       c,
			Vector:     vectors[i],
		}
	}

	if err := r.Store.UpsertChunks(ctx, records); err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}

	r.Logger.Info("graphql upload complete",
		"filename", file.Filename,
		"file_id", fileID,
		"chunks", len(chunks))

	return &model.UploadResult{
		FileID:   fileID,
		Filename: file.Filename,
		Chunks:   len(chunks),
	}, nil
}

// AddText is the resolver for the addText field.
func (r *mutationResolver) AddText(ctx context.Context, text string, name string) (*model.UploadResult, error) {
	if text == "" {
		return nil, fmt.Errorf("text is required")
	}

	chunks := chunker.Chunk(text, r.ChunkConf)
	if len(chunks) == 0 {
		return nil, fmt.Errorf("text produced no chunks")
	}

	vectors, err := r.Embedder.EmbedBatch(ctx, chunks)
	if err != nil {
		return nil, fmt.Errorf("embed: %w", err)
	}

	fileID := uuid.NewString()
	records := make([]store.Chunk, len(chunks))
	for i, c := range chunks {
		records[i] = store.Chunk{
			FileID:     fileID,
			Filename:   name,
			ChunkIndex: i,
			Text:       c,
			Vector:     vectors[i],
		}
	}

	if err := r.Store.UpsertChunks(ctx, records); err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}

	r.Logger.Info("graphql addText complete",
		"name", name,
		"file_id", fileID,
		"chunks", len(chunks))

	return &model.UploadResult{
		FileID:   fileID,
		Filename: name,
		Chunks:   len(chunks),
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, limit *int) (*model.SearchResponse, error) {
	k := 5
	if limit != nil && *limit > 0 {
		k = *limit
	}

	vec, err := r.Embedder.Embed(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("embed query: %w", err)
	}

	hits, err := r.Store.Search(ctx, vec, uint64(k))
	if err != nil {
		return nil, fmt.Errorf("search: %w", err)
	}

	results := make([]*model.SearchResult, len(hits))
	for i, h := range hits {
		results[i] = &model.SearchResult{
			Score:      float64(h.Score),
			FileID:     h.FileID,
			Filename:   h.Filename,
			ChunkIndex: int(h.ChunkIndex),
			Text:       h.Text,
		}
	}

	return &model.SearchResponse{
		Query:   query,
		Results: results,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
