// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type SearchResponse struct {
	Query   string          `json:"query"`
	Results []*SearchResult `json:"results"`
}

type SearchResult struct {
	Score      float64 `json:"score"`
	FileID     string  `json:"fileID"`
	Filename   string  `json:"filename"`
	ChunkIndex int     `json:"chunkIndex"`
	Text       string  `json:"text"`
}

type UploadResult struct {
	FileID   string `json:"fileID"`
	Filename string `json:"filename"`
	Chunks   int    `json:"chunks"`
}
